// LOGIN
export const STORE_TOKEN = 'STORE_TOKEN';
export const UPDATE_LOGIN_INPUT_TEXT = 'UPDATE_LOGIN_INPUT_TEXT';

// GET ALL TRANSACTIONS
export const UPDATE_FEED = 'UPDATE_FEED';

// CREATE NEW EXPENSE
